# Generated by Django 5.2.1 on 2025-06-06 16:18

import django.core.validators
import recipes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранные рецепты",
                "verbose_name_plural": "Избранные рецепты",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мои подписки",
                "verbose_name_plural": "Мои подписки",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Введите название ингредиента",
                        max_length=200,
                        verbose_name="Название ингредиента",
                    ),
                ),
                (
                    "measurement_unit",
                    models.CharField(
                        help_text="Введите единицу измерения",
                        max_length=200,
                        verbose_name="Единица измерения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ингредиент",
                "verbose_name_plural": "Ингредиенты",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="IngredientRecipe",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveSmallIntegerField(
                        help_text="Укажите количество ингредиента",
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Минимальное количество ингредиентов 1"
                            ),
                            django.core.validators.MaxValueValidator(
                                32000, "Максимальное количество ингредиентов 32000"
                            ),
                        ],
                        verbose_name="Количество",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cостав рецепта",
                "verbose_name_plural": "Состав рецепта",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Введите название рецепта",
                        max_length=200,
                        verbose_name="Название рецепта",
                    ),
                ),
                (
                    "cooking_time",
                    models.PositiveSmallIntegerField(
                        help_text="Укажите время приготовления рецепта в минутах",
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Минимальное время приготовления"
                            ),
                            django.core.validators.MaxValueValidator(
                                32000, "Максимальное время приготовления"
                            ),
                        ],
                        verbose_name="Время приготовления",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Опишите приготовление рецепта",
                        max_length=256,
                        verbose_name="Описание рецепта",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default=None,
                        help_text="Добавьте изображение рецепта",
                        upload_to="recipes/images/",
                        verbose_name="Картинка рецепта",
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
                "ordering": ["-pub_date"],
                "default_related_name": "recipe",
            },
        ),
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Список покупок",
                "verbose_name_plural": "Список покупок",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ShortLink",
            fields=[
                (
                    "short_code",
                    models.CharField(
                        default=recipes.models.generate_short_code,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("destination", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Short Link",
                "verbose_name_plural": "Short Links",
            },
        ),
    ]
