# Generated by Django 5.2.1 on 2025-06-04 15:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "ordering": ["id"],
                "verbose_name": "Избранные рецепты",
                "verbose_name_plural": "Избранные рецепты",
            },
        ),
        migrations.AlterModelOptions(
            name="follow",
            options={
                "ordering": ["id"],
                "verbose_name": "Мои подписки",
                "verbose_name_plural": "Мои подписки",
            },
        ),
        migrations.AlterModelOptions(
            name="ingredientrecipe",
            options={
                "ordering": ["id"],
                "verbose_name": "Cостав рецепта",
                "verbose_name_plural": "Состав рецепта",
            },
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "default_related_name": "recipe",
                "ordering": ["-pub_date"],
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
        migrations.AlterModelOptions(
            name="shoppingcart",
            options={
                "ordering": ["id"],
                "verbose_name": "Список покупок",
                "verbose_name_plural": "Список покупок",
            },
        ),
        migrations.AlterField(
            model_name="ingredientrecipe",
            name="amount",
            field=models.PositiveSmallIntegerField(
                help_text="Укажите количество ингредиента",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Минимальное количество ингредиентов 1"
                    ),
                    django.core.validators.MaxValueValidator(
                        32000, "Максимальное количество ингредиентов 32000"
                    ),
                ],
                verbose_name="Количество",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                help_text="Автор рецепта",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор рецепта",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveSmallIntegerField(
                help_text="Укажите время приготовления рецепта в минутах",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Минимальное время приготовления"
                    ),
                    django.core.validators.MaxValueValidator(
                        32000, "Максимальное время приготовления"
                    ),
                ],
                verbose_name="Время приготовления",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                default=None,
                help_text="Добавьте изображение рецепта",
                upload_to="recipes/images/",
                verbose_name="Картинка рецепта",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                through="recipes.IngredientRecipe",
                to="recipes.ingredient",
                verbose_name="Ингредиенты",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="text",
            field=models.TextField(
                help_text="Опишите приготовление рецепта",
                max_length=256,
                verbose_name="Описание рецепта",
            ),
        ),
        migrations.AlterConstraint(
            model_name="follow",
            name="no_self_following",
            constraint=models.CheckConstraint(
                condition=models.Q(("user", models.F("author")), _negated=True),
                name="no_self_following",
                violation_error_message="Нельзя подписаться на самого себя",
            ),
        ),
    ]
