# Generated by Django 5.2.1 on 2025-06-04 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="users/avatars/",
                verbose_name="Аватар",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "Пользователь"), ("admin", "Администратор")],
                default="user",
                max_length=150,
                verbose_name="Пользовательская роль",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Имя пользователя может содержать только буквы,         цифры и @/./+/-/_",
                        regex="^[\\w.@+-]+\\Z",
                    )
                ],
                verbose_name="Логин",
            ),
        ),
    ]
